<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="cuiyishuodeMacBook-Pro.local" ignored="0" name="api测试用例" tests="7" failures="1" timestamp="04 八月 2020 02:19:38 GMT" time="2.955" errors="0">
  <testcase name="loginTrue" time="0.687" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="loginTrue" time="0.262" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="loginFalse" time="0.025" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="loginFalse" time="0.028" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="loginFalse" time="0.024" classname="com.wanmen.cases.users.LoginTest"/>
  <testcase name="share" time="0.27" classname="com.wanmen.cases.users.FavoriteTest"/>
  <testcase name="share" time="0.302" classname="com.wanmen.cases.users.FavoriteTest">
    <failure type="java.lang.AssertionError" message="expected [5] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [0]
	at com.wanmen.cases.users.FavoriteTest.share(FavoriteTest.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- share -->
</testsuite> <!-- api测试用例 -->
